### PR TITLE
Re-Adding commit of letting Bayshore run on newer node.js

### PR DESCRIPTION
**Pull request by leezhiwei**
Have added the changes as per previously, but with new changes (changing default ALL.NET port for convenience, updating opentelemetry (old packages causing issues). If @lostkagamine can review this would be great thanks!

### CODE REVIEW

**Comment by leezhiwei** [comment]
Referencing #79

**Comment by leezhiwei** [comment]
I had an old change, rebased.

**Comment by lostkagamine** [comment]
OpenTelemetry support was never completed and can be removed, I'll look through the rest of the PR now

**Review by lostkagamine — APPROVED** [review]
Looks good, great work.

**Pull request merged**
